This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file /Users/acharyaprvn/git/DCU_Phd_Thesis_Template/.texpadtmp/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/acharyaprvn/git/DCU_Phd_Thesis_Template/.texpadtmp/thesis.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file /Users/acharyaprvn/git/DCU_Phd_Thesis_Template/.texpadtmp/thesis.acr....done (9 lines written, 0 warnings).
Output written in /Users/acharyaprvn/git/DCU_Phd_Thesis_Template/.texpadtmp/thesis.acr.
Transcript written in /Users/acharyaprvn/git/DCU_Phd_Thesis_Template/.texpadtmp/thesis.alg.
